### ISSUE TITLE
(Nice to have) Enable use of bitcoin notifier for new block

### ISSUE THREAD

**Issue by nicklello** [p2pool/p2pool#280]
Replace/make switchable the new block detection in favour of a small bitcoin notifier script.

This would probably alleviate a lot of the load on the bitcoin p2p channel as we wont need to continuously check for the current block height,

**Comment by forrestv** [comment]
P2Pool doesn't use polling to get notification of new blocks - it makes a
P2P connection (port 8333) and listens for block inv messages there.

The load on bitcoind is due to asking for a new block template every 15
seconds in order to get new transactions. It's not time critical, and could
possibly be reduced even further, but polling every 15 seconds being a
problem is a sign of deeper problems.

**Comment by nicklello** [comment]
Understood... but it's unnecessary load, p2pool could be far leaner if it were to use a notifier process; of course this may need to be a per-coin configurable as not all wallets will have this feature.

**Comment by forrestv** [comment]
Erm, where's the unnecessary load? As I said, P2Pool doesn't poll to detect
block changes; it polls to get new transactions. A notifier process
wouldn't help with that.

I could be missing something - which RPC call are you seeing a lot of?

**Comment by nicklello** [comment]
It may be due my use of bitcoinxtd rather than bitcoin core but the p2p thread is consuming vast amounts of CPU on my setup; however if there is a notifier (ie: bitcoin*d does the work to determine a block change) why not use it and reduce CPU usage.

I do not believe the high load is due to the frequency of RPC calls but more down to the bitcoin p2p code.
