### ISSUE TITLE
How can I mining the Dogecoin with P2pool?

### ISSUE THREAD

**Issue by RESBI** [p2pool/p2pool#337]
I found many guide in Google said:"--net dogecoin",
but it can't be run.....
"run_p2pool: error: argument --net: invalid choice: 'dogecoin' (choose from 'bitcoin','fastcoin','litecoin','terracoin')"

**Comment by coinflow** [comment]
Maybe look here:
https://github.com/Rav3nPL/p2pool-rav/issues/97

p2pool-rav has many networks "preinstalled", but DOGE was obviously pulled, because of switching to merged mining.

The supported networks: https://github.com/Rav3nPL/p2pool-rav/tree/master/p2pool/networks

Maybe a start to alter/change/tailor one of these to Dogecoin?

**Comment by RESBI** [comment]
Thanks!
