### ISSUE TITLE
litecoin connection issue

### ISSUE THREAD

**Issue by dtlgc** [p2pool/p2pool#365]
I Have p2pool running good with bitcoin, but cannot get p2pool to connect to litecoin

017-11-29 09:09:49.911001 Testing bitcoind RPC connection to 'http://127.0.0.1:10332/' with username 'litecoinrpcusername'...
2017-11-29 09:09:49.930140 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2017-11-29 09:09:56.396620 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!

litecoin.conf
rpcuser=litecoinrpcusername
rpcpassword=thisisapassword
txindex=1
server=1
daemon=1
rpcbind=127.0.0.1
rpcallowedip=127.0.0.1
rpcport=10332
port=10333

p2p-litecoin.conf
--net litecoin

litecoin version =   "version": 140200

any suggestions?

**Comment by dtlgc** [comment]
looks like to change in code here took care of my issue:
https://github.com/ilsawa/p2pool-ltc/commit/2af67a8cc7d0c498479f080f0652e02c4c826497

reference from this thread
https://github.com/litecoin-project/litecoin/issues/371

**Comment by Alan911Black** [comment]
@dtlgc 
Hi,
can you share how did you solved that issue? the link donot work anymore, thanks!

**Comment by dtlgc** [comment]
Hmmm - not sure which file to look in now, I would suggest giving ilsawa litecoin branch a try
https://github.com/ilsawa/p2pool-lit

**Comment by dtlgc** [comment]
I found it in ./p2pool/p2pool/bitcoin/networks/litecoin.py
change

RPC_CHECK = defer.inlineCallbacks(lambda bitcoind: defer.returnValue(
            'litecoinaddress' in (yield bitcoind.rpc_help()) and
            (yield bitcoind.rpc_getblockchaininfo())['chain'] != 'test'
        ))
to

RPC_CHECK = defer.inlineCallbacks(lambda bitcoind: defer.returnValue(
(yield helper.check_genesis_block(bitcoind, '12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2'))
        ))

Let me know if that does it....

**Comment by Alan911Black** [comment]
the p2pool-lit is 3 years old, i did try your other suggestion but it also didn't work. same error

**Comment by antoinebouchard** [comment]
I can't for the life of me get p2pool to connect to anything - most of the addresses in the litecoin.py for bootstrat don't work (I can't ping) and I don't know if that's my issue - but all I get is the following:

Unhandled Error
Traceback (most recent call last):
  File "/opt/node/p2pool/p2pool/main.py", line 675, in run
    reactor.run()
  File "/home/abouchard/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/abouchard/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
  File "/home/abouchard/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/opt/node/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/opt/node/p2pool/p2pool/work.py", line 210, in preprocess_request
    raise jsonrpc.Error_for_code(-12345)(u'p2pool is not connected to any peers')
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is not connected to any peers

If I disable bootstrap (PERSIST = False), then the error goes away but looking in the code it doesn't seem like the right thing to do since it still means I have no peers connected (self.node.p2p_node is None or len(self.node.p2p_node.peers) == 0) and self.node.net.PERSIST).
I'm running on latest, along with latest litecoind

Looks like the bootstrap addrs haven't been touched in over a year...

**Comment by farsider350** [comment]
#411 Bootstraps do need updating. You can use -n ***.***.***.*** in the startup command to add a known node for now.

**Comment by CBDMINER** [comment]
I'm getting the same error on the new p2pool version 17

**Comment by farsider350** [comment]
This repo is not maintained and it is recommended to use https://github.com/jtoomim/p2pool
