### ISSUE TITLE
Will not install Cryptography

### ISSUE THREAD

**Issue by Thenexus96** [p2pool/p2pool#370]
So I've been searching the internet for a while and hit a bump. So I'm trying to get p2pool running on my Late 2011 MBP and continue to get the "Invalid Environment marker: Python_verson < '3"
I've been looking to see if i can change the default Python used for the program since I found the framework files for Python 3.6 on my system since it wasn't located where the Apple pre-built Python.Framwork files were. And since I'm still new to all of this (Like this week) I would love some help and hopefully I can learn something new. Thank you

P.S.
Here's my pip log for reference
[pip.log](https://github.com/p2pool/p2pool/files/1644941/pip.log)

**Comment by kbirand** [comment]
Same here .... any solution ?

**Comment by bluciano2** [comment]
same for me I trying to install p2pool node on Debian GNU/Linux 9 (stretch)
I have both Python 2.7.13 and Python 3.5.3
the default if I do python --version is Python 2.7.13
with alias python=python3
python --version is Python 3.5.3
it download cryptography-2.1.4.tar.gz
  Running setup.py (path:/home/linaro/p2pool/.pyenv/build/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

It seems as setup.py egg_info use only Python 2.7.13

but  cryptography-2.1.4 needs Python 3.5.3

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/linaro/p2pool/.pyenv/build/cryptography

so it does not install cryptography

I tried 
p2pool$ sudo pip3 install -r requirements.txt
Successfully installed Automat-0.6.0 
Twisted-17.9.0 argparse-1.4.0 asn1crypto-0.24.0 attrs-17.4.0 cffi-1.11.4
 constantly-15.1.0
 cryptography-2.1.4 
hyperlink-18.0.0 idna-2.6 incremental-17.5.0 pyOpenSSL-17.5.0 pycparser-2.18 zope.interface-4.4.3

but in this way I miss the make of  /home/linaro/p2pool/run_p2pool.py

Any suggestion?

**Comment by VERTlG0** [comment]
same problem here building on GNU/Linux Gentoo x86_64 with python version 2.7, 3.4, and 3.6. I tried building it with 3.4 first..then tried 2.7, and finally upgraded my Python to 3.6 with no success. 

I read in other threads the problem lies with upgdating pip and setuptools but I have the latest and suffice to say.. the problem is still here.

**Comment by farsider350** [comment]
P2pool installation with pypy -- Windows

On Windows, pypy is only supported via the Windows Subsystem for Linux (WSL). P2pool on pypy on WSL is much faster than P2pool on
CPython on native Windows. To install WSL, first follow the steps outlined here:

https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

Once you've done that, run bash and follow the rest of the steps below.

P2pool installation with pypy -- Linux and Windows

Copy and paste the following commands into a bash shell in order to install p2pool on Windows or Linux.

sudo apt-get update
sudo apt-get install pypy pypy-dev pypy-setuptools gcc build-essential git

wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo pypy
sudo rm setuptools-*.zip

wget https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.3.tar.gz#md5=9ae3d24c0c7415deb249dd1a132f0f79
tar zxf zope.interface-4.1.3.tar.gz
cd zope.interface-4.1.3/
sudo pypy setup.py install
cd ..
sudo rm -r zope.interface-4.1.3*

wget https://pypi.python.org/packages/source/T/Twisted/Twisted-15.4.0.tar.bz2
tar jxf Twisted-15.4.0.tar.bz2
cd Twisted-15.4.0
sudo pypy setup.py install
cd ..
sudo rm -r Twisted-15.4.0*

git clone https://github.com/jtoomim/p2pool.git
cd p2pool
git checkout 1mb_segwit

You'll also need to install and run your bitcoind or altcoind of choice, and edit ~/.bitcoin/bitcoin.conf (or the corresponding file for litecoin or whatever other coin you intend to mine) with your bitcoind's RPC username and password. Launch your bitcoind or altcoind, and after it has finished downloading blocks and syncing, go to your p2pool directory and run

pypy run_p2pool.py

jtoomimnet vs mainnet

If you wish to use the original forrestv btc mainnet instead of jtoomimnet, then replace

git clone https://github.com/jtoomim/p2pool.git
cd p2pool
git checkout 1mb_segwit

above with

git clone https://github.com/p2pool/p2pool.git
cd p2pool

**Comment by Fawnzy7** [comment]
(path:/home/linaro/p2pool/.pyenv/build/cryptography/setup.py)
