### ISSUE TITLE
No Payout or Expected Share time, Block network errors

### ISSUE THREAD

**Issue by Mentors4EDU** [p2pool/p2pool#403]
![screenshot from 2018-09-12 12-57-21](https://user-images.githubusercontent.com/12502053/45440839-6c63f680-b68b-11e8-8dc5-dff18fca770d.png)
Hi, there seems to be a huge problem with the stats, the time to share and time to block have been always stuck at 3 or 2 seconds. Also there is no predicted payout time and revenue isn't showing up in any of the wallet addresses. The network block difficulty isn't showing up in my UI. Does the problem have to do with the version of BTC Core I am running 0.15 or does it have to do with the version of P2Pool I am using and should try switching over from the mainnet? Any suggestions would be greatly appreciated?

**Comment by Mentors4EDU** [comment]
Any suggestions, especially on why the Network block difficulty isn't showing up @forrestv @farsider350

**Comment by farsider350** [comment]
The problem is within the Web Ui that you are using. Try this one instead.
https://github.com/farsider350/node-stats-btc

**Comment by Mentors4EDU** [comment]
Other pools with the same UI don't seem to be experiencing it, but wondering how come even though the pool is validating shares, nothing is being sent to my BTC wallets yet @farsider350

**Comment by farsider350** [comment]
You are using Mainnet which has a block time of over 3000days at time of writing this. Jtoomimnet has 25PHs right now, 13days to block. http://crypto.office-on-the.net:9332/static/ 
To use Jtoomim's chain use these instructions:

P2pool installation with pypy -- Windows

On Windows, pypy is only supported via the Windows Subsystem for Linux (WSL). P2pool on pypy on WSL is much faster than P2pool on
CPython on native Windows. To install WSL, first follow the steps outlined here:

https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

Once you've done that, run bash and follow the rest of the steps below.

P2pool installation with pypy -- Linux and Windows

Copy and paste the following commands into a bash shell in order to install p2pool on Windows or Linux.

sudo apt-get update
sudo apt-get install pypy pypy-dev pypy-setuptools gcc build-essential git

wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo pypy
sudo rm setuptools-*.zip

wget https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.3.tar.gz#md5=9ae3d24c0c7415deb249dd1a132f0f79
tar zxf zope.interface-4.1.3.tar.gz
cd zope.interface-4.1.3/
sudo pypy setup.py install
cd ..
sudo rm -r zope.interface-4.1.3*

wget https://pypi.python.org/packages/source/T/Twisted/Twisted-15.4.0.tar.bz2
tar jxf Twisted-15.4.0.tar.bz2
cd Twisted-15.4.0
sudo pypy setup.py install
cd ..
sudo rm -r Twisted-15.4.0*

git clone https://github.com/jtoomim/p2pool.git
cd p2pool
git checkout 1mb_segwit

You'll also need to install and run your bitcoind or altcoind of choice, and edit ~/.bitcoin/bitcoin.conf (or the corresponding file for litecoin or whatever other coin you intend to mine) with your bitcoind's RPC username and password. Launch your bitcoind or altcoind, and after it has finished downloading blocks and syncing, go to your p2pool directory and run

pypy run_p2pool.py

jtoomimnet vs mainnet

If you wish to use the original forrestv btc mainnet instead of jtoomimnet, then replace

git clone https://github.com/jtoomim/p2pool.git
cd p2pool
git checkout 1mb_segwit

above with

git clone https://github.com/p2pool/p2pool.git
cd p2pool

Note: The BTC p2pools currently have low hashrate, which means that payouts will be infrequent, large, and unpredictable. As of Feb 2018, blocks are found on jtoomimnet on average once every 25 days, and blocks are found on mainnet on average once every 108 days. Do not mine on BTC p2pool unless you are very patient and can tolerate receiving no revenue for several months.


Miner setup

P2pool communicates with miners via the stratum protocol. For BTC, configure your miners with the following information:

URL: stratum+tcp://(Your node's IP address or hostname):9332
Worker: (Your bitcoin address)
Password: x

For Litecoin, replace 9332 with 9327. For Bitcoin Cash, use 9348. For Dash, use 7903.

The mining address must be a regular P2PKH address. Segwit, multisig, and bech32 addresses are not supported. That means an address starting with a 1 for Bitcoin or Bitcoin Cash or an L for Litecoin. If you use an address that p2pool cannot understand, then p2pool will mine to that node's default address instead.

If you wish to modify the mining difficulty, you may add something like "address+4096" after your mining address to set the pseudoshare difficulty to 4096, or "address/65536" to set the actual share difficulty to 65536 or the p2pool minimum share difficulty, whichever is higher. Pseudoshares only affect hashrate statistics, whereas actual shares affect revenue variance and efficiency.


Firewall considerations

If your node is behind a firewall or behind NAT (i.e. on a private IP address), you may want to forward ports to your p2pool server. P2pool uses two ports: one for p2p communication with the p2pool network, and another for both the web UI and for stratum communication with workers. For Bitcoin, those ports are 9333 (p2p) and 9332 (stratum/web). For Litecoin, they are 9326 (p2p) and 9327 (stratum/web). For Bitcoin Cash, they are 9349 (p2p) and 9348 (stratum/web).

**Comment by farsider350** [comment]
If you don't like to wait around for blocks but still want to use p2pool then give Digibyte a mine.
https://github.com/farsider350/p2pool-dgb-sha256-350.git

**Comment by farsider350** [comment]
For all p2pool discussion you can refer to https://forum.bitcoin.com/pools/p2pool-decentralized-dos-resistant-trustless-censorship-resistant-pool-t69932.html

**Comment by farsider350** [comment]
@Mentors4EDU please close the issue as it has nothing to do with the code having a problem. If you still think the Web UI needs fixing please open an issue in the repository of the Web UI code.

**Comment by Mentors4EDU** [comment]
@farsider350 @jtoomim After switching to jtoomim's network, it keeps saying:
`
Unhandled Error
Traceback (most recent call last):
  File "/home/chainterra/P2Pool_BTC/p2pool/main.py", line 666, in run
    reactor.run()
  File "/home/chainterra/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "/home/chainterra/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1270, in mainLoop
    self.runUntilCurrent()
  File "/home/chainterra/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/home/chainterra/P2Pool_BTC/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/home/chainterra/P2Pool_BTC/p2pool/work.py", line 210, in preprocess_request
    raise jsonrpc.Error_for_code(-12345)(u'p2pool is not connected to any peers')
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is not connected to any peers
`
Is this a problem that will just go away after few hours or why is it appearing?

**Comment by farsider350** [comment]
add    --p2pool-node crypto.office-on-the.net    to the starting command if the problem persists.
ie. pypy run_p2pool.py --p2pool-node crypto.office-on-the.net

**Comment by Mentors4EDU** [comment]
> add --p2pool-node crypto.office-on-the.net to the starting command if the problem persists.
> ie. pypy run_p2pool.py --p2pool-node crypto.office-on-the.net

Nope, still the same error

**Comment by jtoomim** [comment]
Something is wrong with your setup and is preventing you from connecting to any peers. If you can't connect to peers, then you can't connect to the p2pool network. Perhaps your firewall is blocking your connections. You could try forwarding port 9333 (for BTC) from your router to your p2pool server, or otherwise messing with your firewall settings.

**Comment by Mentors4EDU** [comment]
> Something is wrong with your setup and is preventing you from connecting to any peers. If you can't connect to peers, then you can't connect to the p2pool network. Perhaps your firewall is blocking your connections. You could try forwarding port 9333 (for BTC) from your router to your p2pool server, or otherwise messing with your firewall settings.

@jtoomim @farsider350 I would like to believe it is a port forwarding error, but when I connect to the main network instead of Jtoomim, it doesn't have such a problem. It won't even load node uptime. Could it be perhaps in the version of Bitcoind I am running? Problem with the main network is an expected block time of over 3.5+ years is unsustainable, and if I fix the peer error then I would obviously have a preference of using the jtoomim network. 

Here is my url:
chain-pool.com:9332

And I use Webmin/Virtualmin for the server's port forwarding

**Comment by jtoomim** [comment]
You probably need to clean out your data/bitcoin directory before switching software version. I suggest installing jtoomimnet into a separate folder.

**Comment by Mentors4EDU** [comment]
@jtoomim How do I clean the data/bitcoin directory, and would I need to resync the daemon again? Where do I find bitcoin's data/bitcoin directory? Is it a private or public directory?

**Comment by jtoomim** [comment]
Just reinstall jtoomim/p2pool in a clean folder.

**Comment by Mentors4EDU** [comment]
Fixed, now downloading shares on the jtoomim network. Just takes some update/synchronization time after fresh install from a new network
