### ISSUE TITLE
farsider350, why are you doing this?

### ISSUE THREAD

**Issue by ilsawa** [p2pool/p2pool#415]
You are writing: https://github.com/p2pool/p2pool/issues/411

To mine Digibyte, you can use these p2pools: https://github.com/farsider350/p2pool-dgb-scrypt-350
https://github.com/farsider350/p2pool-dgb-sha256-350
https://github.com/farsider350/p2pool-dgb-skein-350

Here are the original sources:
https://github.com/ilsawa/p2pool-dgb-scrypt
https://github.com/ilsawa/p2pool-dgb-sha256
https://github.com/ilsawa/p2pool-dgb-skein
https://github.com/ilsawa/p2pool-dgb-qubit
https://github.com/ilsawa/p2pool-dgb-groestl

**Comment by Alardnet** [comment]
Maybe he likes stealing someone else's code and giving it away for his own?

https://github.com/farsider350/node-stats-ltc
original sources:
https://github.com/justino/p2pool-ui-punchy

**Comment by ilsawa** [comment]
Here too https://github.com/jtoomim/p2pool/pull/16/files#diff-04c6e90faac2675aa89e2176d2eec7d8R132

https://github.com/jtoomim/p2pool/pull/16

**Comment by farsider350** [comment]
Removed. 
Would you like to update your readme to accommodate Win10 and PYPY? That way I can reference your repo instead. I'm doing it for ease of install and adoption of p2pool for new comers. I will concentrate on licencing and giving credit where due.

**Comment by ilsawa** [comment]
farsider350
What does pypy do for the code itself?
I am correcting the code, and in my readme recommendations for python.
You fixed the readme, and recommends for all using your repository.

Coins of a thousand, make p2pool for those who do not have it, and give links to your repository.

**Comment by jtoomim** [comment]
Pypy is only particularly useful with coins that have either high transaction volume, low block/share times, or both. This mostly means BTC, LTC, and (during stress tests only) BCH. Most other coins can be efficiently mined with regular CPython, which uses less RAM.

**Comment by farsider350** [comment]
Ilsawa,
With the use of your readme file. Digibyte_subsidy, Python Skein Hash and Litecoin Scrypt Modules fail to build on freshly installed Ubuntu 18.04 everytime, I was fairly certain it used to happen on Ubuntu 17.
Using pypy instructions that Jtoomim has implemented into BTC p2pool work perfectly for your repo and modules. Installs flawlessy every single time without a worry at all to the end user. I thought by now that the issue would have been resolved. I think we need 'ease of use' for adoption. Multiple people have been turned off p2pool because of setup issues. Are we trying to turn people away or get more people into the space?

Jtoomim
Now I'm no expert thats for sure, but in saying pypy is particularly useful to coins with low block/share times. Wouldn't pypy be useful to Digibyte considering it has 15 sec block times? Works quite well for me and others that have used the pypy setup.

**Comment by jtoomim** [comment]
Oh I didn't realize Digibyte had such short block times. Yes, pypy would likely be helpful in that case.
